[config]

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/modules/themes/matugen_colors.lua"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/matugen-colors.rasi"
