# Auto-generated by Matugen
return {
    wallpaper = "{{image}}",

    primary = "{{colors.primary.dark.hex}}",
    on_primary = "{{colors.on_primary.dark.hex}}",
    primary_container = "{{colors.primary_container.dark.hex}}",
    on_primary_container = "{{colors.on_primary_container.dark.hex}}",

    secondary = "{{colors.secondary.dark.hex}}",
    on_secondary = "{{colors.on_secondary.dark.hex}}",

    background = "{{colors.background.dark.hex}}",
    on_background = "{{colors.on_background.dark.hex}}",
    surface = "{{colors.surface.dark.hex}}",
    on_surface = "{{colors.on_surface.dark.hex}}",
}
