# Auto-generated by Matugen
return {
    wallpaper = "/home/wang/Pictures/wallhaven-5yr3m1.jpg",

    primary = "#a1cafd",
    on_primary = "#003259",
    primary_container = "#1a4975",
    on_primary_container = "#d2e4ff",

    secondary = "#bbc7db",
    on_secondary = "#253140",

    background = "#111418",
    on_background = "#e1e2e8",
    surface = "#111418",
    on_surface = "#e1e2e8",
}
