# Auto-generated by Matugen
return {
    wallpaper = "/home/wang/Pictures/skull.jpg",

    primary = "#ffb4a8",
    on_primary = "#561e16",
    primary_container = "#73342a",
    on_primary_container = "#ffdad4",

    secondary = "#e7bdb6",
    on_secondary = "#442925",

    background = "#1a1110",
    on_background = "#f1dfdb",
    surface = "#1a1110",
    on_surface = "#f1dfdb",
}
