# Core Colors
background            #1a1110
foreground            #f1dfdb
selection_foreground  #ffb4a8
selection_background  #561e16
cursor                #ffb4a8
cursor_text_color     #1a1110

# Regular Colors
color0  #1a1110               
color1  #ffb4ab                 
color2  #ffb4a8               
color3  #dec48c              
color4  #ffdad4  
color5  #ffdad4
color6  #e7bdb6             
color7  #f1dfdb            

# Bright Colors
color8  #423735         
color9  #ffb4ab                  
color10 #ffb4a8                
color11 #dec48c               
color12 #ffdad4   
color13 #ffdad4 
color14 #e7bdb6              
color15 #f1dfdb             
